### 查询单条数据
GET http://{{url}}/productCategories/1

### 查询分页数据
GET http://{{url}}/productCategories?page=1&pageSize=10

### 删除数据
DELETE http://{{url}}/productCategories/1

### 更新数据
PUT http://{{url}}/productCategories
Content-Type: application/json

{
  "id": 1,
  "code": "1",
  "name": "2",
  "icon": "qwe",
  "categoryFlag": null,
  "status": "0"
}

### 新增数据
POST http://{{url}}/productCategories
Content-Type: application/json

{
  "code": "1",
  "name": "2",
  "icon": "qwe",
  "categoryFlag": null,
  "status": "0",
  "delFlag": "0"
}